config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#tasks'
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#details", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def tasks
    @all = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def details
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/details.html.erb
<div class='container m-2'>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= @task.title %></h5>
      <p class="card-text"><%= @task.details %></p>
      <%= link_to("Back", tasks_path, {class: 'btn btn-primary'}) %>
      <%= link_to("Edit", edit_task_path(@task), {class: 'btn btn-primary'}) %>
      <%= link_to("Delete", destroy_task_path(@task), {method: :delete, class: 'btn btn-primary'}) %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/tasks.html.erb
<div class="container-lg">
  <h1>My tasks</h1>
  <ul class="list-group">
    <% @all.each do |task| %>
      <li class="list-group-item">
      <% if task.completed %>
        <input class="form-check-input me-1" type="checkbox" checked>
        <label> <%= link_to task.title, task_path(task) %> </label>
      <% else %>
        <input class="form-check-input me-1" type="checkbox">
        <label> <%= link_to task.title, task_path(task) %> </label>
        </li>
      <% end %>
    <%end%>
  </ul>

  <div style="display: flex" class="mt-3">
    <%= link_to("Create a new task", tasks_new_path) %>
  </div>
</div>